### PR TITLE
Translate logger descriptions and names. Block alignments.

### PR DESCRIPTION
**Pull request by kebbet**
Translate descriptions and names (for loggers) and align code blocks in `getInfo`-functions for the loggers.

### CODE REVIEW

**Comment by kebbet** [comment]
Maybe the names should not be translated? Will translation of them break something @bonny ?

**Comment by bonny** [comment]
Thanks for this! I think the names can be translated too. It should be the `slug` of each logger that is used to store events and search them and so on. 🤔

**Comment by kebbet** [comment]
Thank for clarification. 

> Thanks for this! I think the names can be translated too. It should be the `slug` of each logger that is used to store events and search them and so on. 🤔

Thanks for clarification! I'll make some suggestions for the ones missing.

**Comment by kebbet** [comment]
Think I'm done now. Please review!

**Review by bonny — APPROVED** [review]
Thanks a lot, I think it looks good 👍

**Pull request merged**
