### PR TITLE
Add support for WPMU plugins

### PR DESCRIPTION
**Pull request by jacquesletesson**
I wanted to use Wordpress-Simple-History as a mu-plugins but It was possible due to wrong file path.

Made two quick modification and the plugin is now compatible as a WPMU plugin.

### CODE REVIEW

**Comment by bonny** [comment]
Thanks! Tested and working. Will include in next version.

**Comment by szepeviktor** [comment]
This is a very interesting feature.

**Comment by szepeviktor** [comment]
Would it be possible to install SH as a normal plugin and activate it through a symlink?

**Comment by szepeviktor** [comment]
Is `plugin_dir_path()` able to handle symlinks?
This setup would be beneficial because of the automatic update. Which is not possible as an mu-plugin.

**Pull request merged**
